# Generated by Django 2.2.6 on 2019-10-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirrurl',
            name='shortcode',
            field=models.CharField(default='cfedefaultshortcode', max_length=220),
            preserve_default=False,
        ),
    ]
